name: Lighthouse audit
on: pull_request

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: 'Wait for deploy preview to finish'
        uses: 'WyriHaximus/github-action-wait-for-status@master'
        with:
          ignoreActions: 'Lighthouse audit'
          checkInterval: 20
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - uses: actions/checkout@v1
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v2
        with:
          urls: |
            https://deploy-preview-${{ github.event.number }}--upbeat-lovelace-3e9fff.netlify.com/
            https://deploy-preview-${{ github.event.number }}--upbeat-lovelace-3e9fff.netlify.com/data
            https://deploy-preview-${{ github.event.number }}--upbeat-lovelace-3e9fff.netlify.com/data/state/washington
            https://deploy-preview-${{ github.event.number }}--upbeat-lovelace-3e9fff.netlify.com/us-daily
          uploadArtifacts: true
          temporaryPublicStorage: true
          budgetPath: ./.github/budget.json
          configPath: ./.github/lighthouserc.json
